try {
	${1}
} catch (${2:ExceptionClass e}) {
	${3}
} finally {
	${4}
}
